const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const folders = await prisma.folder.findMany();
  
  const yearRegex = /^\d{4}$/;
  const months = ['january','february','march','april','may','june','july','august','september','october','november','december'];
  
  let updatedCount = 0;
  for (const f of folders) {
    if (!f.isAutoGenerated && (yearRegex.test(f.name) || months.includes(f.name.toLowerCase()))) {
      await prisma.folder.update({
        where: { id: f.id },
        data: { isAutoGenerated: true }
      });
      console.log(`Updated folder: ${f.name}`);
      updatedCount++;
    }
  }
  
  console.log(`Successfully updated ${updatedCount} old system folders.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
